Add query option to api doc
openvstorage/ovs-documentation pull request #73
Opened 2017-12-04 13:43 UTC by JeffreyDevloo

2017-12-04 14:23 UTC, kvanhijf requested changes

2017-12-04 14:23 UTC, kvanhijf commented on Administration/usingtheapi/README.md
> +                    -   'size' is lesser than 100,
less than

2017-12-08 14:50 UTC, wimpers commented
Do not merge this PR unless we a package with this version in the OSE repo.

2018-05-17 07:20 UTC, sjovdnbos approved these changes

2019-07-25 07:13 UTC, merged